# Generated by Django 2.1.7 on 2019-03-05 14:27

from django.db import migrations
import django_zombodb.operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        django_zombodb.operations.ZomboDBExtension(),
    ]
